### PR TITLE
Paul branch

### PR DESCRIPTION
**Pull request by paulmah**
just added a comment to paul2.txt

### CODE REVIEW

**Review by vincentcui5296 — APPROVED** [review]
GOod

**Comment by paulmah** [comment]
i took notes during the video, but was missing something.  it all made sense, but doing it helps.  thanks for your guidance, vincent 🙂

regards,
paul

________________________________

**Comment by vincentcui5296** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    welcome, and practice makes perfect. :)
        hope you are all doing well.Yu
    
        
            
        
    
    
        
        

        
    

    On 3/18/2020 16:07，paulmah<notifications@github.com> wrote： 




i took notes during the video, but was missing something.  it all made sense, but doing it helps.  thanks for your guidance, vincent 🙂







regards,



paul







________________________________

**Comment by paulmah** [comment]
to do list: pending from josh



Yu Cui
3:38 PM
yes
Sijo Kottappuram Jacob
3:40 PM
hello
guys
You
3:40 PM
we can hear you
Sijo Kottappuram Jacob
3:40 PM
can u hear me guys
Joshua VanderBrink
3:40 PM
We can hear you
You
3:40 PM
i can hear josh
Joshua VanderBrink
3:40 PM
Is your mic muted?
Yu Cui
3:44 PM
now we don't need to decide backend.
.net is the backend.
so we only need to front end: html css js
css, we suggest to use bootstrap
Yu Cui
3:46 PM
bootstrap is used widely, and have strong community support.
Yu Cui
3:48 PM
?
I can understand you.
yes
Yu Cui
3:53 PM
I suggest each one can do a part of the page.
both html and css.
Joshua VanderBrink
3:53 PM
I am kind of thinking the same thing Vincent i just don't know how to say it properly lol
Yu Cui
3:54 PM
because a page contains a lot of parts, nav, aside, main.
Joshua VanderBrink
3:57 PM
https://drive.google.com/drive/u/1/folders/18BhbVWUM4bSq_fLxGc27pqqSvT2Fbgso<https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fdrive.google.com%2Fdrive%2Fu%2F1%2Ffolders%2F18BhbVWUM4bSq_fLxGc27pqqSvT2Fbgso>
Joshua VanderBrink
3:58 PM
https://drive.google.com/drive/u/1/folders/18BhbVWUM4bSq_fLxGc27pqqSvT2Fbgso<https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fdrive.google.com%2Fdrive%2Fu%2F1%2Ffolders%2F18BhbVWUM4bSq_fLxGc27pqqSvT2Fbgso>
Yu Cui
4:00 PM
sure
we also need to use trello to split tasks later.
Yu Cui
4:02 PM
yes
team leader is split tasks to everyone
we need a PM that is our team leader.
Yu Cui
4:04 PM
I only like coding.
Yu Cui
4:05 PM
every one should review the code in github after someone push code into github.
You
4:09 PM
which code?
Yu Cui
4:10 PM
I mean, when someone complete some code for prcilla project, others should review the code and add some comments.
You
4:12 PM
agreed to the code review. we should utilize github and work on our branches and push back for pull review and integration
Yu Cui
4:14 PM
the code can be merged only after all team members approve.
You
4:15 PM
agreed
Yu Cui
4:22 PM
are vvfr4s b.l;likvn
Yu Cui
4:24 PM
L
25254551
Yu Cui
4:27 PM
Y78O8UYHUTRDEETYRTEEERTFGERTETR
NO
my daughter is typing
I have no problem.
Yu Cui
4:28 PM
no problem.
javascript is really hard.
see you
You
4:29 PM
see you :-)

**Comment by paulmah** [comment]
Yu Cui
1:05 PM
7808073296
paul: 780-901-6352
Joshua VanderBrink
2:07 PM
780-266-8490
Sijosol Jacob
2:08 PM
5875687621

**Pull request merged**
